# Generated by Django 3.2.6 on 2021-08-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carbodytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbodyname', models.CharField(blank=True, db_column='CarBodyName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'CarBodyType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(blank=True, db_column='ModelName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'CarModel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, db_column='State', max_length=45, null=True)),
            ],
            options={
                'db_table': 'CarState',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carvender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carvendername', models.CharField(blank=True, db_column='CarVenderName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'CarVender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivetype',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
            ],
            options={
                'db_table': 'DriveType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelname', models.CharField(blank=True, db_column='FuelName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'FuelType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearboxcotype', models.CharField(blank=True, db_column='GearBoxcoType', max_length=45, null=True)),
            ],
            options={
                'db_table': 'GearBox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('inginvolume', models.FloatField(blank=True, db_column='InginVolume', null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=45, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True, db_column='CreationDate', null=True)),
                ('Image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='car_imgs')),
                ('is_published', models.BooleanField(blank=True, default=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'SellRequest',
                'managed': False,
            },
        ),
    ]
