# Generated by Django 3.2.6 on 2021-08-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, db_column='Country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, db_column='PostCode', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, db_column='Street', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, db_column='Surname', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.IntegerField(blank=True, db_column='Telephone', null=True),
        ),
    ]
